# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapm" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "d550ad908b8abc31545aca1a412224696ea7d6e8ecc91b61aee0a3e322532638"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf4c31a9f6434435438b88e9f700c353e7a8a5a6b3a0fb8dd7577e381004e5fc"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5bbce27beaf3cfce54d278f2e2d8b9228f99c9778885039d4f1a68a9ab594e33"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "71952ead33776a4fb793da024a9a706183cd8d7a5cfc2efdb58e1bd6a639e0d0"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kapm"
  desc "Kiro Agent Package Manager"
  homepage "https://github.com/kapmcli/kapm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapm"]
    end
  end

  # No zap stanza required

end
