# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapm" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "051041344b87710753a14a52c746a616fd7b8827b1d9e0557740d70e8fc1f6e8"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51befa9975156c84b8e7de42987a4ae2114ef313866c5c7a64a49a2ca5e1df93"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4f2f18f6c03823bd5d0f331673f9a8ae28259e7e21fe4268cf3af6c7d2585e2"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "54384773c1003a88eacbcf2e0c921bcea2c84d11a90aae89ef4d760f0d6ec992"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kapm"
  desc "Kiro Agent Package Manager"
  homepage "https://github.com/kapmcli/kapm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapm"]
    end
  end

  # No zap stanza required

end
