# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapm" do
  version "0.10.2"

  on_macos do
    on_intel do
      sha256 "45a45c32aad5b6808a3892e412ac75b42f3080a4159a2e715defa13faa6afd2a"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fc5f888389dfc5ba612a208b9f5d1014f1c4ca81ad34568ae1148ba8ca267e9"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "431ab18622fc11b0a735dea64558fa88c2be39ba630c60023337ee30b0c8d244"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9727f054b6351f7444a04e4e07d73ea9231f1ade1d3beb8e445ae06930340445"
      url "https://github.com/kapmcli/kapm/releases/download/v#{version}/kapm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kapm"
  desc "Kiro Agent Package Manager"
  homepage "https://github.com/kapmcli/kapm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapm"]
    end
  end

  # No zap stanza required

end
